name: nostri
services:
  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    command: conda run -n fastapi_env uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: _frontend
    container_name: vite_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host
